openapi: '3.0.3'
info:
  title: Genius Yield Bot API
  description: Open API Specificaion of the Genius Yield Bot API for trading strategy integration.
  version: '0.1.0'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    Settings:
      type: object
      properties: {
          network: { type: string },
          version: { type: string },
          revision: { type: string },
          backend: { type: string }
        }
      example:
       { network: "mainnet", version: "0.1.0", revision: "c7cc91eec7f3d50b8de196a01034b0cc7097ae59", backend: "mmb" }
    Fees:
      type: object
      properties: {
          place: { type: string },
          cancel: { type: string },
          maker: { type: string },
          taker: { type: string }
        }
      example:
       { network: "mainnet", version: "0.1.0", revision: "c7cc91eec7f3d50b8de196a01034b0cc7097ae59", backend: "mmb" }
    Market:
      type: object
      required: [market_id, base_currency, target_currency, pool_id, last_price, base_volume, target_volume, liquidity_in_usd]
      properties:
        market_id: { type: string, description: "Identifier of a ticker with delimiter to separate base/target, eg. ADA/GENS" }
        base_asset: { type: string, description: "Ticker of a the base cryptoasset, eg. ADA" }
        target_asset: { type: string, description: "Symbol of the target cryptoasset, eg. GENS" }
        # Coin Gecko API requirements spec (out of scope for now):
        # pool_id: { type: string, description: "Unique ID of the trading pair" }
        # last_price: { type: number, format: double, description: "Last transacted price of base currency based on given target currency (unit in base or target) eg. X = ?, 1 base = X target, X base = 1 target" }
        # base_volume: { type: number, format: double, description: "24 hour trading volume for the pair (unit in base)" }
        # target_volume: { type: number, description: "24 hour trading volume for the pair (unit in target)" }
        # liquidity_in_usd: { type: string, description: "Trading pair liquidity in USD" }
        # bid: { type: number, format: double, description: "Current highest bid price" }
        # ask: { type: number, format: double, description: "Current lowest ask price" }
        # high: { type: number, format: double, description: "Rolling 24-hours highest transaction price" }
        # low: { type: number, format: double, description: "Rolling 24-hours lowest transaction price" }
      example:
       { market_id: "ADA/GENS", base_asset: "ADA", target_asset: "GENS" }
    Markets:
      type: array
      items: {$ref: '#/components/schemas/Market'}
    Order:
      type: object
      properties:
        market_id: { type: string, description: "Identifier of a ticker with delimiter to separate base/target, eg. ADA/GENS" }
        timestamp: { type: string, format: "date", example: "1985-04-12T23:00:00.00Z" }
        base_amount: { type: number, format: double, description: "Transaction amount in base pair volume." }
        target_amount: { type: number, format: double, description: "Transaction amount in target pair volume." }
      example:
        {
          "market_id" : "ADA/GENS",
          "timestamp" : "1985-04-12T23:00:00.00Z",
          "base_amount" : 49.9,
          "target_amount" : 50.1
        }
    Orders:
      type: array
      items: {$ref: '#/components/schemas/Order'}
    Trade:
      type: object
      required: [market_id, base_asset, target_asset, pool_id, last_price, base_volume, target_volume, liquidity_in_usd]
      properties:
        trade_id: { type: string, description: "Identifier of a ticker with delimiter to separate base/target, eg. ADA/GENS" }
        base_volume: { type: number, format: double, description: "Transaction amount in base pair volume." }
        target_volume: { type: number, format: double, description: "Transaction amount in target pair volume." }
        trade_timestamp: { type: integer, description: "Unix timestamp in milliseconds for when the transaction occurred." }
        type: { type: string, description: "Used to determine the type of the transaction that was completed. Buy: Identifies an ask that was removed from the order book. Sell: Identifies a bid that was removed from the order book." }
    Trades:
      type: array
      items: {$ref: '#/components/schemas/Trade'}
      example:
        [
         { "trade_id":1234567, "price":"50.1", "base_volume":"0.1", "target_volume":"1", "trade_timestamp":"1700050000", "type":"buy" },
         { "trade_id":1234567, "price":"50.1", "base_volume":"0.1", "target_volume":"1", "trade_timestamp":"1700050000", "type":"sell" }
        ]
    Price:
      type: object
      properties:
        base_close: { type: number, format: double, description: Base close }
        base_high: { type: number, format: double, description: Target high }
        base_low: { type: number, format: double, description: Base low }
        base_open: { type: number, format: double, description: Base open }
        base_volume: {type: number, format: double, description: Base volume }
        target_close: { type: number, format: double, description: Target close }
        target_high: { type: number, format: double, description: Target high }
        target_low: { type: number, format: double, description: Target low }
        target_open: { type: number, format: double, description: Target open}
        target_volume: { type: number, format: double, description: Target volume }
        count: { type: integer, description: Candlestick size }
        time_period_start: { type: string , description: Trade timestamp, format: "date", example: "1985-04-12T23:00:00.00Z" }
        time_period_end: { type: string , description: Trade timestamp, format: "date", example: "1985-04-12T23:15:00.00Z" }
    Prices:
      type: array
      items: {$ref: '#/components/schemas/Price'}
security:
  - ApiKeyAuth: [read, write]
tags: [{name: markets}, {name: orders}, {name: trades}, {name: prices}, {name: settings}]
externalDocs:
 description: Bot API Documentation
 url: https://www.bot-api-docs.geniusyield.co/
servers:
  - url: https://localhost:4000/
  - url: https://bot.api.geniusyield.co/
paths:
  /settings:
    get:
      tags: [settings]
      responses: { 200: {description: successful operation, content: {application/json: {schema: {$ref: '#/components/schemas/Settings' }}}}}
  /markets:
    get:
      tags: [markets]
      responses: { 200: {description: successful operation, content: {application/json: {schema: {$ref: '#/components/schemas/Markets' }}}}}
  /orders:
    parameters:
     - {in: query, name: market_id, required: true, schema: { type: string }}
     - {in: query, name: depth, required: false, schema: { type: integer }}
    get:
      tags: [orders]
      responses: { 200: {description: successful operation, content: {application/json: {schema: {$ref: '#/components/schemas/Orders' }}}}}
    post:
      tags: [orders]
      responses: {201: {description: Created}}
    delete:
      tags: [orders]
      responses: {202: {description: Deleted}}
  /historical_trades:
    parameters:
     - {in: query, name: market_id, required: true, schema: { type: string }}
     - {in: query, name: type, required: false, schema: { type: string, enum: ["buy", "sell"], example: "buy" }}
     - {in: query, name: limit, required: false, schema: { type: integer, example: "100" }}
     - {in: query, name: page, required: false, schema: { type: integer, example: "1" }}
     - {in: query, name: start_time, required: false, schema: { type: string, format: "date", example: "1996-12-19T16:39:57-08:00" }}
     - {in: query, name: end_time, required: false, schema: { type: string, format: "date", example: "1996-12-19T17:39:57-08:00" }}
    get:
      tags: [trades]
      responses: { 200: {description: successful operation, content: {application/json: {schema: {$ref: '#/components/schemas/Trades' }}}}}
  /historical_prices:
    parameters:
     - {in: query, name: market_id, required: true, schema: { type: string }}
     - {in: query, name: resolution, required: false, schema: { type: string, enum: ["1m", "5m", "15m", "30m", "1h", "4h", "1d", "1w", "1mo"], example: "30m" }}
     - {in: query, name: from, required: false, schema: { type: string, format: "date", example: "2024-12-03" }}
     - {in: query, name: to, required: false, schema: { type: string, format: "date", example: "2024-12-04" }}
     - {in: query, name: limit, required: false, schema: { type: integer, example: "100" }}
     - {in: query, name: page, required: false, schema: { type: integer, example: "1" }}
     - {in: query, name: sort, required: false, schema: { type: string, enum: [asc, desc] }}
    get:
      tags: [price]
      responses: { 200: {description: successful operation, content: {application/json: {schema: {$ref: '#/components/schemas/Prices' }}}}}
  /trading_fees:
    get:
      tags: [fees]
      responses: { 200: {description: successful operation, content: {application/json: {schema: {$ref: '#/components/schemas/Fees' }}}}}
