# Sample bot configuration for Mainnet.

mbc_user:
  ur_s_key_path: path-to-skey
  ur_coll: tx-id#tx-ix
  ur_stake_address: bech32-encoded-stake-address
mbc_delay: 120000000
mbc_price_config:
  pc_api_key: <<MAESTRO_TOKEN>>
  pc_resolution: 15m
  pc_network_id: mainnet
  # `pc_dex` supports either `minswap` or `genius-yield`.
  pc_dex: minswap
# Please see `README.md` for details regarding `mbc_strategy_config` field.
mbc_strategy_config:
  sc_spread:
    numerator: 1
    denominator: 100
  sc_token_volume:
    tv_sell_min_vol: 1000000000
    tv_buy_min_vol: 2000000000
    tv_sell_budget: 3500000000
    tv_buy_budget: 6600000000
    tv_sell_vol_threshold: 10000000000
    tv_buy_vol_threshold: 20000000000
  sc_price_check_product: 9
  sc_cancel_threshold_product: 4
# Token details.
mbc_token:
  # Asset class represented as concatenation of currency symbol and asset name with dot separator.
  ac: dda5fdb1002f7389b33e036b6afee82a8189becb6cba852e8b79b4fb.0014df1047454e53
  # Registered decimal places for the token. As an examples, for `ADA` it is 6 and for `SNEK` it is 0.
  precision: 6
# Boiler plate for Mainnet.
mbc_fp_nft_policy: compiled-scripts/minting-policy
mbc_fp_order_validator: compiled-scripts/partial-order
mbc_po_config_addr: addr1w9zr09hgj7z6vz3d7wnxw0u4x30arsp5k8avlcm84utptls8uqd0z
mbc_po_refs:
  por_ref_nft: fae686ea8f21d567841d703dea4d4221c2af071a6f2b433ff07c0af2.4aff78908ef2dce98bfe435fb3fd2529747b1c4564dff5adebedf4e46d0fc63d
  por_val_ref: 062f97b0e64130bc18b4a227299a62d6d59a4ea852a4c90db3de2204a2cd19ea#2
  por_mint_ref: 062f97b0e64130bc18b4a227299a62d6d59a4ea852a4c90db3de2204a2cd19ea#1