name: build

on:
  push:
    branches: [ "update-maestro-sdk" ]
  pull_request:
    branches: [ "update-maestro-sdk" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # updated tag for the update-maestro-sdk branch:
            type=raw,value=updated,enable=true
      - name: ${{ github.ref == 'refs/heads/update-maestro-sdk' && 'Build and Push Docker image' || 'Build Docker image' }}
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.ref == 'refs/heads/update-maestro-sdk'}}
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
